### ISSUE TITLE
Cannot start node-red in IBM Cloud

### ISSUE THREAD

**Issue by Ayumu-walker** [ibmets/node-red-bluemix-starter#32]
v0.6.0

The same phenomenon as problem 26 also occurred on the IBM Cloud. The same fixes made the problem resolved. Is this correct as an official solution?
https://github.com/ibmets/node-red-bluemix-starter/issues/26

**Comment by knolleary** [comment]
If you get that error running in the IBM Cloud it means the starter has not been able to find the Cloudant database instance, so is falling back to localfilesystem and hitting the error.

You should not use localfilesystem on IBM Cloud - the filesystem is not persistent between application restarts. So whilst #26 does need addressing (and not using the change suggested as that will not work with later versions of Node-RED), your issue is whatever has meant it was unable to find cloudant.

**Comment by Ayumu-walker** [comment]
Thank you so much for your answer!
After changing the Cloudant service name to include it in the application name, the deployment succeeded.
